dcrm/dcrm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

dcrm/website/urls.py
# imports views file in the same directory
from . import views
from django.urls import path

app_name = 'website'

urlpatterns = [
    path("", views.index, name="home"),
    path("login/", views.login_user, name="login"),
    path("register/", views.register_user, name="register"),
    path("logout/", views.logout_user, name="logout"),
    path("record/<int:pk>", views.customer_record, name="record"),
    path("delete/<int:pk>", views.delete_customer, name="delete"),
    path("add/", views.add_record, name="add"),
    path("update/<int:pk>", views.update_record, name="update")
]

dcrm/website/models.py
from django.db import models

# Create your models here.
class Record(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=50)


    def __str__(self):
        return(f"{self.first_name} {self.last_name}")

dcrm/website/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Record


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(label="", max_length="50", widget=forms.TextInput(attrs={'class': 'first-name', 'placeholder':'First Name', 'autocomplete': 'off'}))
    last_name = forms.CharField(label="", max_length="50", widget=forms.TextInput(attrs={'class': 'last-name', 'placeholder':'Last Name', 'autocomplete': 'off'}))
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class': 'email', 'placeholder': 'Email Address', 'autocomplete': 'off'}))



    class Meta:
        model = User

        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'username'
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['username'].widget.attrs['autocomplete'] = 'off'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="notice">Think of something different. Same usernames will be rejected.</span>'

        self.fields['password1'].widget.attrs['class'] = 'password1'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = ''

        self.fields['password2'].widget.attrs['class'] = 'password2'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="notice">Passwords must match.</span>'



class AddRecordForm(forms.ModelForm):
    first_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'First Name', 'class': 'first-name', 'autocomplete': 'off'}), label="")
    last_name = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'Last Name', 'class': 'last-name', 'autocomplete': 'off'}), label="")
    email = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'Email', 'class': 'email', 'autocomplete': 'off'}), label="")
    phone = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={"placeholder": "Phone", "class": "phone", 'autocomplete': 'off'}), label="")
    address = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'Address', 'class': 'address', 'autocomplete': 'off'}), label="")
    city = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'City', 'class': 'city', 'autocomplete': 'off'}), label="")
    state = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'State', 'class': 'state', 'autocomplete': 'off'}), label="")
    zipcode = forms.CharField(required=True, widget=forms.widgets.TextInput(attrs={'placeholder': 'Zipcode', 'class': 'zipcode', 'autocomplete': 'off'}), label="")


    class Meta:
        model = Record
        exclude = ("user",)

dcrm/website/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import SignUpForm, AddRecordForm
from .models import Record



# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect("website:login")

    records = Record.objects.all()

    return render(request, 'index.html', {'records': records})


# login page
def login_user(request):
    if request.method == "POST":
        # get the info the user typed
        username = request.POST['username']
        password = request.POST['password']

        # authenticate user
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.success(request, "You have been Logged in")
            return redirect('website:home')
        else:
            messages.error(request, "Something went wrong, Try again")
            return redirect("website:login")
        
    # if the method is GET
    else:
        return render(request, 'login.html', {})



# logout function   
def logout_user(request):
    logout(request)
    messages.success(request, "You have been logged out...")
    return redirect("website:login")



# register page
def register_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            # authenticate user and log user in
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']

            user = authenticate(username=username, password=password)
            login(request, user)

            messages.success(request, "You have successfully registerd, welcome")
            return redirect("website:home")

    else:
        form = SignUpForm()
        return render(request, 'register.html', {'form': form})
    
    return render(request, 'register.html', {'form': form})
    

def customer_record(request, pk):
    if request.user.is_authenticated:
        customer_record = Record.objects.get(id=pk)
        return render(request, 'record.html', {'customer_record': customer_record})
    
    else:
        messages.error(request, "You do not have access to this page")
        return redirect("website:login")


def delete_customer(request, pk):
    if request.user.is_authenticated:
        delete_record = Record.objects.get(id=pk)

        delete_record.delete()
        messages.success(request, "Record deleted successfully")
        return redirect("website:home")
    
    else:
        messages.error(request, "You dont have access to this page")
        return redirect("website:login")
    

def add_record(request):
    form = AddRecordForm(request.POST or None)

    if request.user.is_authenticated:
        if request.method == "POST":
            if form.is_valid():
                form.save()
                messages.success(request, "Record Added")
                return redirect("website:home")

        return render(request, "add_record.html", {'form': form})
    else:
        messages.error(request, "You do not have access to this page")
        return redirect("website:home")
    

def update_record(request, pk):
    if request.user.is_authenticated:
        current_record = Record.objects.get(id=pk)
        form = AddRecordForm(request.POST or None, instance=current_record)
        if form.is_valid():
            form.save()
            messages.success(request, "Record has been updated")
            return redirect("website:home")
        
        return render(request, "update_record.html", {'form': form})
    
    else:
        messages.error(request, "You must be logged in")
        return redirect("website:home")

dcrm/website/templates/add_record.html
{% extends 'layout.html' %}

{% block body %}

<div class="container">
    <div class="form-container">
        <h1>Add a new record</h1>

        <form class="form" method="post" action="{% url 'website:add' %}">
            {% csrf_token %}
            {{ form.as_p }}
    
            <button type="submit" class="add-record-btn">Add Record</button>
            <button class="back-btn"><a href="{% url 'website:home' %}">Back</a></button>
        </form>
    </div>
</div>

{% endblock %}

dcrm/website/templates/index.html
{% extends 'layout.html' %}

{% block body %}


<div class="container">
    <h1 class="records-title">Records</h1>
    <p class="tate">*Click on the ID for settings</p>

            <table id="records">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Creation Time</th>
                        <th>Address</th>
                        <th>City</th>
                        <th>State</th>
                        <th>Zipcode</th>
                    </tr>
                </thead>

                <tbody>
                    {% if records %}
                        {% for record in records %}
                            <tr>
                                <td><a href="{% url 'website:record' record.id %}" class="individual-record">{{ record.id }}</a></td>
                                <td>{{ record.first_name }} {{ record.last_name }}</td>
                                <td>{{ record.email }}</td>
                                <td>{{ record.phone }}</td>
                                <td>{{ record.created_at }}</td>
                                <td>{{ record.address }}</td>
                                <td>{{ record.city }}</td>
                                <td>{{ record.state }}</td>
                                <td>{{ record.zipcode }}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                </tbody>
            </table>

    <p></p>
</div>

{% endblock %}

dcrm/website/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website App</title>
    <link href="{% static 'styles/styles.css' %}" rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"> -->
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>

    <header class="header">
        {% include 'navbar.html' %}
    </header>


    <div class="containerr the-message">
        <div style="background-color: #f7d6da; border-radius: .375rem; max-width: 500px; margin: 2rem auto; display: flex; justify-content: space-between; align-items: center;">
            {% if messages %}
            <div style="padding: .5rem 1rem;">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </div>
            <button class="close-button">X</button>
        {% endif %}
        </div>
    </div>

    <main class="main">
        {% block body %}
        {% endblock %}
    </main>

</body>
</html>

dcrm/website/templates/login.html
{% extends 'layout.html' %}

{% block body %}

    <div class="container">
        <div class="content-wrapper-login">
            <div class="content-inner-wrapper-login">
                <div class="info">
                    <h1>Welcome back</h1>
                    <p>New here? <a href="{% url 'website:register' %}">Register</a></p>
                </div>
        
                <form action="{% url 'website:login' %}" method="post">
                    {% csrf_token %}
                    <div class="input-wrapper">
                        <input type="text" name="username" placeholder="Username" autocomplete="off">
                    </div>
            
                    <div class="input-wrapper">
                        <input type="password" placeholder="Password" name="password">
                    </div>                    
            
                    <input type="submit" value="Login" class="login-btn">
                </form>
            </div>
        </div>
       
    </div>

{% endblock %}

dcrm/website/templates/navbar.html
<nav class="navbar">
    <!-- change this -->
    <a href="{% url 'website:home' %}" class="logo">Django CRM</a>

    <ul class="link-wrapper">

        {% if user.is_authenticated %}
            <li class="link-list">
                <a href="{% url 'website:logout' %}">Logout</a>
            </li>
            <li class="link-list">
                <a href="{% url 'website:add' %}">Add Record</a>
            </li>
        {% else %}
            <li class="link-list">
                <a href="{% url 'website:login' %}">Login</a>
            </li>

            <li class="link-list">
                <a href="{% url 'website:register' %}">Register</a>
            </li>
        {% endif %}
    </ul>
</nav>

dcrm/website/templates/record.html
{% extends 'layout.html' %}

{% block body %}

<div class="container">
    <div class="customer-info">
        <div class="customer-name">
            <p><strong>{{ customer_record.first_name }} {{ customer_record.last_name }}</strong></p>
        </div>

        <ul class="customer-info-wrapper">
            <li><span class="bold">Address: </span>{{ customer_record.address }}</li>
            <li><span class="bold">City: </span>{{ customer_record.city }}</li>
            <li><span class="bold">State: </span>{{ customer_record.state }}</li>
            <li><span class="bold">Phone: </span>{{ customer_record.zipcode }}</li>
            <li><span class="bold">Creation Time: </span>{{ customer_record.created_at }}</li>
            <li><span class="bold">ID: </span>{{ customer_record.id }}</li>
        </ul>
    </div>

    <div class="perform-actions">
        <div class="btn-wrapper back">
            <a href="{% url 'website:home' %}">Back</a>
        </div>

        <div class="btn-wrapper update">
            <a href="{% url 'website:update' customer_record.id %}">Update Record</a>
        </div>

        <div class="btn-wrapper delete">
            <a href="{% url 'website:delete' customer_record.id %}">Delete</button>
        </div>
    </div>
</div>


{% endblock %}

dcrm/website/templates/register.html
{% extends 'layout.html' %}

{% block body %}

<div class="container">

    <div class="content-wrapper">
        <div class="content-inner-wrapper">
            <div class="top-info">
                <span>start for free</span>
                <h1>Create new account.</h1>
                <p>Already a member? <a href="{% url 'website:login' %}">Log in</a></p>
            </div>
    
            <div class="form-wrapper">
                <form method="post" action="">
                    {% csrf_token %}
                    <!-- {% if form.errors %}
                        {% for field in form %}
                            {% if field.errors %}
                                {{ field.errors }}
                            {% endif %}
                        {% endfor %}
                    {% endif %} -->
                    <div class="form-inner-wrapper">
                        {{ form.as_p }}
                        <input type="submit" value="Register" class="submit-button">
                    </div>

    
                </form>
            </div>
        </div>
    </div>

</div>

{% endblock %}

dcrm/website/templates/update_record.html
{% extends 'layout.html' %}

{% block body %}

    <div class="container">
        <div class="form-container">
            <h1>Update record</h1>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="add-record-btn">Update Record</button>
                <button class="back-btn"><a href="{% url 'website:home' %}">Back</a></button>

            </form>

        </div>


    </div>

{% endblock %}